### ISSUE TITLE
🤔 [ Question ]: 战神材料攻打出现失败

### ISSUE THREAD

**Issue by wlireland353** [LauZzL/leitingzhanji-ui#100]
### 系统版本
windows 11

### 程序版本
3.1.4

### 详细描述你的问题
闯关 - 材料 - 战神
在这个模式下攻打战神材料时，大概剩下8-9个关卡时，会出现攻打失败，刷新个人信息也会显示获取信息失败，接着关闭软件后再打开会显示不允许海外地区，等了将近几分钟后再打开软件又正常了

不知道其他人有没有这个问题？
### 截图 (如果可以)
忘记截图了

**Comment by ASCIIX** [comment]
你的请求太快，IP被拉黑了

**Comment by wlireland353** [comment]
> 你的请求太快，IP被拉黑了

是这个原因吗，但我没改呀，是默认的1000ms

**Comment by LauZzL** [comment]
我们将在下个版本对一些功能进行重构，该问题可能会随之解决，将于小程序下次版本更新后上线。
