### ISSUE TITLE
🚀 [ Feature ]: 希望可以增加一个PVP“成功挑战次数”的选择

### ISSUE THREAD

**Issue by FunnyMudChouPee** [LauZzL/leitingzhanji-ui#101]
#### 你希望增加的功能？
希望在PVP金币场功能区增加一个
①“一键完成今日10次金币对战”类似的按钮，同时
②保留当前的可选次数功能，
并新增一个③停止匹配 功能

#### 为什么？
①因为pvp不是总是稳定匹配到的，有时候挂着匹配转头回来看并不知道成功匹配了多少次，需要刷新小程序才能看见，因此如果把匹配次数改成“成功匹配次数”或者是新增一个一键完成今日pvp积分获取会方便很多，也符合本程序的“减少操作量”的核心思路
②有时候使用pvp功能的时候剩余金币场可获取积分次数并不都是10次，保留一个自选功能模块的话软件功能覆盖面更广
③若是匹配时间过长的话，能自己选择取消匹配等待之后再重新匹配

**Comment by wlireland353** [comment]
在软件上刷新个人信息即可，不过最新版本我遇到个人信息刷新无显示的bug，其他功能暂时正常
