### ISSUE TITLE
🚀 [ Feature ]: 希望能够重置无尽模式历史最高分

### ISSUE THREAD

**Issue by A7749** [LauZzL/leitingzhanji-ui#102]
#### 你希望增加的功能？
重置无尽模式历史最高分

#### 为什么？
无尽历史最高分过高，无法正常进行PVP模式游玩，具体为PVP匹配不到人

**Comment by LauZzL** [comment]
...

**Comment by ASCIIX** [comment]
> #### 你希望增加的功能？
> 重置无尽模式历史最高分
> 
> #### 为什么？
> 无尽历史最高分过高，无法正常进行PVP模式游玩，具体为PVP匹配不到人

可以，把你UID给我，我去让官方清。

**Comment by Lanassel** [comment]
> > #### 你希望增加的功能？
> > 重置无尽模式历史最高分
> > #### 为什么？
> > 无尽历史最高分过高，无法正常进行PVP模式游玩，具体为PVP匹配不到人
> 
> 可以，把你UID给我，我去让官方清。

笑死我了

**Comment by iLinglingling** [comment]
> ...

把作者都干沉默了
