### ISSUE TITLE
🐛 [ Bug ]: 3.1.5版本是否主动取消了暗黑/明亮模式的切换按钮

### ISSUE THREAD

**Issue by FunnyMudChouPee** [LauZzL/leitingzhanji-ui#103]
#### 您使用的版本？
3.1.5

#### 系统版本？
Windows11 232

#### 您遇到了什么问题？
3.1.5新版更新是否是否主动取消了暗黑/明亮模式的切换按钮？亦或者将此按钮移动到别的功能模块区域？如果是bug建议修复，如果是主动取消希望能加回来，暗黑模式比明亮模式使用感受更为舒适清晰，谢谢

#### 请提供错误截图？
3.1.5版本
![WYCV}KSSYFS4(1}AMXD@YML](https://github.com/user-attachments/assets/9322b365-17af-47d3-9212-d9f2e0eef9a1)

3.1.4版本
![image](https://github.com/user-attachments/assets/26fb9869-9f73-4f12-b142-b5c23734037d)

**Comment by LauZzL** [comment]
已修复 删除程序目录Cache文件夹后重新打开即可
