### ISSUE TITLE
🐛 [ Bug ]: 疑似bug，谨慎使用，官方更改了PVP规则，以及初始化删除了一个数据包。

### ISSUE THREAD

**Issue by ASCIIX** [LauZzL/leitingzhanji-ui#105]
#### 您使用的版本？
3.1.5

#### 系统版本？
Windows 10 ，22H2， 19045.3208

#### 您遇到了什么问题？
1. 请不要开始PVP，否则无法退出。
2. 关于初始化之后，无法获取个人信息，答：官方将这个数据包删除了。

#### 请提供错误截图？
1. 如果已开启PVP，请删除缓存，或者等第二天。
![18](https://github.com/user-attachments/assets/4feb61fa-0942-4848-9fe4-8f604912a913)

**Comment by 2503272265** [comment]
和我的情况一样

**Comment by LauZzL** [comment]
1. 进行不了PVP无法复现
2. 测试获取正常

**Comment by ASCIIX** [comment]
官方的问题，已手动恢复。
