### ISSUE TITLE
🐛 [ Bug ]: 无法展示个人信息

### ISSUE THREAD

**Issue by 2503272265** [LauZzL/leitingzhanji-ui#106]
#### 您使用的版本？
3.1.5

#### 系统版本？

Win10
#### 您遇到了什么问题？
获取不到个人信息

#### 请提供错误截图？

![雷霆战机脚本bug](https://github.com/user-attachments/assets/334a6b2b-115e-4b47-b44c-4d21c8ce1a41)

**Comment by LauZzL** [comment]
经测试正常获取 未能复现该情况

**Comment by 2503272265** [comment]
> 经测试正常获取 未能复现该情况

情况是里面的功能能用，就是个人信息界面看不到，刷新和初始化也没用，还是和上图一样

**Comment by wlireland353** [comment]
> 经测试正常获取 未能复现该情况

我也是遇到了这个问题

**Comment by Mofan1379** [comment]
出现这种情况是因为你之前在背包满了的情况下，强制执行了pvp匹配

**Comment by LauZzL** [comment]
> 我也是遇到了这个问题

在JavaScript页面，执行获取个人信息脚本看是否能正常输出信息，请在该issue中与我反馈

**Comment by 2503272265** [comment]
> 出现这种情况是因为你之前在背包满了的情况下，强制执行了 pvp匹配

我的背包没满过

**Comment by 2503272265** [comment]
> > 我也是遇到了这个问题
> 
> 在JavaScript页面，执行获取个人信息脚本看是否能正常输出信息，请在该issue中与我反馈

能正常输出，就是显示不了信息

**Comment by LauZzL** [comment]
> 能正常输出，就是显示不了信息

尝试使用3.1.4版本看是否能正常显示，可能是由于背包展示引起的错误，但在开发环境测试无法复现错误

**Comment by 2503272265** [comment]
> > 能正常输出，就是显示不了信息
> 
> 尝试使用3.1.4版本看是否能正常显示，可能是由于背包展示引起的错误，但在开发环境测试无法复现错误

强制更新，用不了3.1.4

**Comment by LauZzL** [comment]
> 强制更新，用不了3.1.4

已关闭了3.1.4的强制更新提示

**Comment by 2503272265** [comment]
> > 能正常输出，就是显示不了信息
> 
> 尝试使用3.1.4版本看是否能正常显示，可能是由于背包展示引起的错误，但在开发环境测试无法复现错误

3.1.4正常

**Comment by 2503272265** [comment]
> > 能正常输出，就是显示不了信息
> 
> 尝试使用3.1.4版本看是否能正常显示，可能是由于背包展示引起的错误，但在开发环境测试无法复现错误

![截图](https://github.com/user-attachments/assets/72663520-09bd-428a-ba1e-49d3af8e2d10)

**Comment by 2503272265** [comment]
> > 强制更新，用不了3.1.4
> 
> 已关闭了3.1.4的强制更新提示

但是现在又强制更新了
![Uploading 截图.png…]()

**Comment by 2503272265** [comment]
> > 强制更新，用不了3.1.4
> 
> 已关闭了3.1.4的强制更新提示

但是现在又强制更新了
![截图](https://github.com/user-attachments/assets/fc497e58-28d7-40ae-bd1a-a3cf2b576855)

**Comment by LauZzL** [comment]
@2503272265  再次尝试3.1.5是否正常 已经移除了背包展示

**Comment by 2503272265** [comment]
> @2503272265 再次尝试3.1.5是否正常 已经移除了背包展示

还是不行

**Comment by LauZzL** [comment]
@2503272265  暂时无法确定问题 如果你可以提供账号测试 请联系我的vk: [LauZzL](https://vk.com/lauzzl)

**Comment by 2503272265** [comment]
> @2503272265 暂时无法确定问题 如果你可以提供账号测试 请联系我的vk: [LauZzL](https://vk.com/lauzzl)

我注册不了这个账号，能用其他方式进行联系吗？

**Comment by LauZzL** [comment]
> 我注册不了这个账号，能用其他方式进行联系吗？

暂无

**Comment by LauZzL** [comment]
@2503272265 在[KOOK](https://kook.top/RlP9by)中联系我

**Comment by Yawning10** [comment]
> @2503272265 在[KOOK](https://kook.top/RlP9by)中联系我

我也遇到了这个问题
![Uploading 屏幕截图 2024-10-20 211532.jpg…]()

**Comment by LauZzL** [comment]
已经修复了该问题 稍后在releases中下载最新版本

**Comment by 2503272265** [comment]
> 已经修复了该问题 稍后在 releases中下载最新版本

修复了，感谢作者的辛勤付出！！！
