### ISSUE TITLE
🐛 [ Bug ]: 3.15打开为什么会闪退...

### ISSUE THREAD

**Issue by avadaqwe** [LauZzL/leitingzhanji-ui#107]
#### 您使用的版本？
3.15

#### 系统版本？
win10、win7

#### 您遇到了什么问题？
打开后窗口一闪就没了，我以为是系统的问题，遂VM装了个win7，也是一模一样，我还去了网吧，下载解压后双击.exe还是一闪就没......
老版本3.14可以打开
#### 请提供错误截图？
QAQ木有截图，太快了手速不够

**Comment by Mofan1379** [comment]
下载这个，安装
https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/consumer/?form=MA13LH

**Comment by avadaqwe** [comment]
> 下载这个，安装 https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/consumer/?form=MA13LH

感谢！已成功运行3.15
