### ISSUE TITLE
🐛 [ Bug ]: 个人信息没法获取

### ISSUE THREAD

**Issue by wlireland353** [LauZzL/leitingzhanji-ui#108]
#### 您使用的版本？
3.1.5

#### 系统版本？
windows 11

#### 您遇到了什么问题？
个人信息显示刷新成功，但未显示

#### 请提供错误截图？
![image](https://github.com/user-attachments/assets/9c1382cb-88ec-4c0b-b652-a4c66072b6dc)

**Comment by wlireland353** [comment]
其他功能暂时未发现问题，正常使用中

**Comment by LauZzL** [comment]
请勿重复创建issue， #106

**Comment by 2503272265** [comment]
一样的情况
