### ISSUE TITLE
🤔 [ Question ]: 提示“启动进程代理失败，请尝试使用管理员运行”，以管理员运行也是这样

### ISSUE THREAD

**Issue by DashSake** [LauZzL/leitingzhanji-ui#112]
### 系统版本
Windows 11 企业版

### 程序版本
3.1.7

### 详细描述你的问题
提示“启动进程代理失败，请尝试使用管理员运行”，以管理员运行也是这样

### 截图 (如果可以)
<img width="791" alt="image" src="https://github.com/user-attachments/assets/4cb5b6a4-2605-45c8-b8c1-850cfe871751">

**Comment by LauZzL** [comment]
使用SunnyNetTools查看是否可以正常打开进程代码：https://github.com/qtgolang/SunnyNetTools

**Comment by DashSake** [comment]
> 使用SunnyNetTools查看是否可以正常打开进程代码：https://github.com/qtgolang/SunnyNetTools

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/2c8ef7c4-2c49-425d-95d3-584501f2cf31">
这样吗？

**Comment by LauZzL** [comment]
设置有一个进程代理 看看能否打开

**Comment by DashSake** [comment]
> Reference in new is

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/9b011a35-4011-4718-bf7d-31798f8c2004">
只看到这个

**Comment by LauZzL** [comment]
那就不清楚了 可能是系统或者驱动问题 进程拦截也是用的SunnyNet提供的
