### ISSUE TITLE
🚀 [ Feature ]: 希望可以在程序里添加清理背包的功能

### ISSUE THREAD

**Issue by ljy1234559** [LauZzL/leitingzhanji-ui#113]
#### 你希望增加的功能？
在程序里添加清理背包的功能，出售，合成，喂经验等等

#### 为什么？

因为在小程序里碰到背包溢出的时候需要退出重进进行清理，不是很便捷，希望加这个功能

**Comment by LauZzL** [comment]
在计划中 且仅在计划中
