### ISSUE TITLE
🤔 [ Question ]: 游戏登陆后自动进入PVP♾️️匹配中

### ISSUE THREAD

**Issue by Gfsxch** [LauZzL/leitingzhanji-ui#114]
### 系统版本
Win10

### 程序版本
最新

### 详细描述你的问题
用完pvp后重新登录自动进入匹配中状态，且已经等待1天&清除缓存，目前仍然是这种情况

### 截图 (如果可以)

https://github.com/user-attachments/assets/a15b1e46-32a4-4242-8f11-35c5c0812a5b

**Comment by LauZzL** [comment]
你可以试试把体力消耗完 再重启小程序试试
或者在KOOK频道问问其他人 他们有遇到过的

**Comment by Gfsxch** [comment]
背包满了，什么都做不了了哇

**Comment by ASCIIX** [comment]
> 背包满了，什么都做不了了哇

官方写的垃圾代码问题。

**Comment by ljy1234559** [comment]
只能等作者大大做出小程序里也能清理背包的功能或者官方再次扩展背包了

**Comment by ljy1234559** [comment]
作者大大新增了一个防卡匹配的功能，进去点一下重新登入就好了
