### ISSUE TITLE
🚀 [ Feature ]:希望可以添加无尽模式(好友)的积分自定义修改

### ISSUE THREAD

**Issue by jslgithub** [LauZzL/leitingzhanji-ui#115]
#### 你希望增加的功能？
自定义修改无尽模式分数(好友榜)

#### 为什么？
霸占朋友榜榜首

**Comment by LauZzL** [comment]
不会添加，这些功能可能会导致PVP异常无法进行或封号，如需使用请用封包或脚本实现
