### ISSUE TITLE
🐛 [ Bug ]: 

### ISSUE THREAD

**Issue by 853097424** [LauZzL/leitingzhanji-ui#118]
#### 您使用的版本？
3.2.2

#### 系统版本？
win11

#### 您遇到了什么问题？
因为我需要使用自定义关卡批量通过未通关的关卡，希望再优化一下自动停止攻打逻辑

**Comment by ASCIIX** [comment]
没有办法，建议手动，并且需要手动解锁关卡。

**Comment by Lia-VI** [comment]
你的脚本被倒卖了，在闲鱼上

**Comment by LauZzL** [comment]
> 你的脚本被倒卖了，在闲鱼上

谢谢你的提醒 但并没有什么办法
