### ISSUE TITLE
🐛 [ Bug ]: 部分模块点击无反应

### ISSUE THREAD

**Issue by mantianxiang** [LauZzL/leitingzhanji-ui#119]
#### 您使用的版本？
3.2.2

#### 系统版本？
win11 22h2

#### 您遇到了什么问题？
除首页以及功能的闯关和日常以外，其他模块点击均无反应

#### 请提供错误截图？

Uploading 屏幕录制 2024-10-30 194857.mp4…

**Comment by mantianxiang** [comment]
https://github.com/user-attachments/assets/64657506-e110-422c-8682-8d65abdc39cf

**Comment by LauZzL** [comment]
删除 `Cache` 文件夹重启

**Comment by mantianxiang** [comment]
> 删除 `Cache` 文件夹重启

收到，谢谢大佬
