### ISSUE TITLE
🐛 [ Bug ]: 运行脚本之后无法打开微信的雷霆战机小程序

### ISSUE THREAD

**Issue by cl13215519502** [LauZzL/leitingzhanji-ui#121]
#### 您使用的版本？
3.2.3

#### 系统版本？
win 11

#### 您遇到了什么问题？
脚本和雷霆战机小程序出现排斥现象，无法同时打开两个程序，雷霆战机小程序始终卡在5%或者不加载进度条，脚本程序也开始出现无法响应的情况，之前的版本是可以正常运行的，新的这一版无法正常运行，已经持续3、4天了

#### 请提供错误截图？
![微信截图_20241101111438](https://github.com/user-attachments/assets/d34b62c0-1d6a-4638-98c1-b5fb1cf303f3)
![微信截图_20241101111914](https://github.com/user-attachments/assets/a747cfb2-699a-40d7-bddd-9cb98fa57883)
![微信截图_20241101112000](https://github.com/user-attachments/assets/eb9f8499-3c24-4611-8bbf-7149882a1ebd)
![微信截图_20241101112418](https://github.com/user-attachments/assets/e40ac944-0b84-4dbc-b816-e52c259dde9b)

**Comment by LauZzL** [comment]
看情况是由于你的网络问题导致的，你可以重启电脑后重试，或使用其他网络。
