### ISSUE TITLE
🐛 [ Bug ]: 

### ISSUE THREAD

**Issue by JXNS-GUO** [LauZzL/leitingzhanji-ui#124]
#### 您使用的版本？
3.2.4

#### 系统版本？
win11

#### 您遇到了什么问题？
闯关和boss模式不可攻打

#### 请提供错误截图？
![fdab7ad27e936bbb1c4bdcbbab17868](https://github.com/user-attachments/assets/8b7077af-779d-4e40-84f1-1adf65a47302)

**Comment by ASCIIX** [comment]
建议自己修，没实力就算了。

**Comment by JXNS-GUO** [comment]
> 建议自己修，没实力就算了。

不会啊实力哥发一个呗

**Comment by JXNS-GUO** [comment]
> 已经存在的issue不要重复提 明白吗

好的明白了，打扰了，感谢大佬，大佬辛苦
