### ISSUE TITLE
🐛 [ Bug ]: PVP刷挑战币和一键闯关功能失效

### ISSUE THREAD

**Issue by Mybabycj** [LauZzL/leitingzhanji-ui#125]
#### 您使用的版本？
3.2.4

#### 系统版本？
win11

#### 您遇到了什么问题？
pvp刷挑战币和一键闯关功能失效

#### 请提供错误截图？
<img width="485" alt="屏幕截图 2024-11-11 232729" src="https://github.com/user-attachments/assets/78668552-efb9-42c5-9771-e33027bcd442">
<img width="496" alt="屏幕截图 2024-11-11 232803" src="https://github.com/user-attachments/assets/9b5d67d8-e657-4548-834b-00afbae5f001">

**Comment by LauZzL** [comment]
已经存在的issue不要重复提 明白吗
