### ISSUE TITLE
🐛 [ Bug ]: 无尽刷宝箱失败

### ISSUE THREAD

**Issue by Mybabycj** [LauZzL/leitingzhanji-ui#126]
#### 您使用的版本？

3.2.4
#### 系统版本？

win11
#### 您遇到了什么问题？

无尽刷宝箱失败
#### 请提供错误截图？
![Uploading 屏幕截图 2024-11-11 233457.png…]()

**Comment by ASCIIX** [comment]
建议自己修，没实力就算了。

**Comment by 2759933691** [comment]
> 建议自己修，没实力就算了。脑子没事吧

**Comment by LauZzL** [comment]
已经存在的issue不要重复提 明白吗
