### ISSUE TITLE
js逆向

### ISSUE THREAD

**Issue by Rx1314** [LauZzL/leitingzhanji-ui#127]
可否公开一下之前的js逆向代码，想参考一下之前是如何逆向的，参考一下之前的思路学习一下

**Comment by LauZzL** [comment]
教程写好了 暂时没来得及发布 因为算法还未失效 所以不会公开的哈

**Comment by Rx1314** [comment]
好的，谢谢博主，等失效了再公开叭，我只是想参考一下，因为之前自己学js逆向还未接触wasm这方面的处理，网上搜了也没有相关的视频，所以现在一头雾水

**Comment by 1821920744** [comment]
> 教程写好了 暂时没来得及发布 因为算法还未失效 所以不会公开的哈

大佬，现在用不了了，还会继续更新吗

**Comment by LauZzL** [comment]
@jslgithub @1821920744 已经修复了 但是由于倒卖代打太多了 暂时不会发布新版本的哈

**Comment by jslgithub** [comment]
可以私发一份不？

**Comment by 1821920744** [comment]
@LauZzL

**Comment by 1821920744** [comment]
每日一蹲
