### ISSUE TITLE
🤔 [ Question ]: 闯关模式刷不了了

### ISSUE THREAD

**Issue by ZhouJiah66** [LauZzL/leitingzhanji-ui#128]
### 系统版本
win10

### 程序版本
v3.2.4

### 详细描述你的问题
闯关模式用不了了，普通和英雄都用不了了

### 截图 (如果可以)
![image](https://github.com/user-attachments/assets/626f5b97-35f0-4b1f-8ea8-3d69084a98f0)

**Comment by LauZzL** [comment]
已经存在的issue不要重复提 明白吗
