### ISSUE TITLE
请问初始化失败，不支持海外地区访问是什么问题呢

### ISSUE THREAD

**Issue by suiyuerg** [LauZzL/leitingzhanji-ui#13]
人在浙江 杭州

**Comment by wlireland353** [comment]
等作者更新吧，今天下午游戏更新了新版本，估计得重新解密

**Comment by suiyuerg** [comment]
无尽匹配半年 难搞

**Comment by Harbin-chenguanxi** [comment]
一样的情况

**Comment by wlireland353** [comment]
> 无尽匹配半年 难搞

你以前无尽刷过分的话，在黑名单里无尽就匹配不到人

**Comment by LauZzL** [comment]
Get! 但我暂时没时间，我需要完成我手头的任务

**Comment by LauZzL** [comment]
done. 我已经完成了1.0.8版本的加解密算法，他将在不久后装配到 最新版本中，谢谢等待~

**Comment by suiyuerg** [comment]
> 做。我已经完成了1.0.8版本的加解密算法，他将在不久后装配到 最新版本中，谢谢等待~

大佬NP 破音~~

**Comment by zhhhh96** [comment]
小程序1.09了

**Comment by Kamikita-Komari** [comment]
佬，怎么定位的加密算法，想学一手

**Comment by Rx1314** [comment]
大佬，请教一下，请问你是反编译小程序还是直接强开小程序调试？

**Comment by LauZzL** [comment]
> 佬，怎么定位的加密算法，想学一手

hook

**Comment by LauZzL** [comment]
> 大佬，请教一下，请问你是反编译小程序还是直接强开小程序调试？

dev tools

**Comment by Rx1314** [comment]
> > 大佬，请教一下，请问你是反编译小程序还是直接强开小程序调试？
> 
> 开发工具
那玩意儿不是会被制裁么，我看这上面有个wechatopendevtools，但是我一直不敢用啊，怕wx号gg

**Comment by LauZzL** [comment]
> 那玩意儿不是会被制裁么，我看这上面有个wechatopendevtools，但是我一直不敢用啊，怕wx号gg

是的 可能会封号

**Comment by LauZzL** [comment]
DONE. 已发布：[LTZJ-NEM.Build.3.0.3](https://github.com/LauZzL/leitingzhanji-ui/releases/tag/v3.0.3)

**Comment by suiyuerg** [comment]
感谢大佬
