### ISSUE TITLE
闯关，获取boss宝箱失败

### ISSUE THREAD

**Issue by dyperi** [LauZzL/leitingzhanji-ui#16]
#### 您使用的版本？

3.0.3

#### 系统版本？

win11

#### 您遇到了什么问题？

闯关，获取boss宝箱失败

#### 请提供错误截图？
攻打失败：亲爱的玩家，不要修改不要作弊不要蒙混过关哦，梦想不能有折扣~
获取宝箱失败：亲爱的玩家，不要修改不要作弊不要蒙混过关哦，梦想不能有折扣~

**Comment by Melodykong** [comment]
me too

**Comment by LauZzL** [comment]
调整Timer值

**Comment by Melodykong** [comment]
已解决 timer30就可以了

**Comment by ylnlh** [comment]
我活动也总是失败，试了几个timer都不行

**Comment by LauZzL** [comment]
> 我活动也总是失败，试了几个timer都不行

timer与战力挂钩 低战力timer可能需要更高

活动失败请查看活动是否开启 体力次数是否足够
