### ISSUE TITLE
🐛 [ Bug ] 证书安装失败

### ISSUE THREAD

**Issue by zzl688vc** [LauZzL/leitingzhanji-ui#19]
#### 您使用的版本？
3.04

#### 系统版本？

win10
#### 您遇到了什么问题？
初始化无法安装证书

#### 请提供错误截图？
![Uploading 屏幕截图 2024-09-14 165908.jpg…]()

**Comment by zzl688vc** [comment]
![Uploading 屏幕截图 2024-09-14 165908.jpg…]()

**Comment by zzl688vc** [comment]
自动安装到系统失败，请手动安装证书。

**Comment by LauZzL** [comment]
下载该文件 [SunnyNetTool.exe](https://wwxa.lanzouj.com/iNHoW28jk46f)，打开后到设置安装证书后即可。

**Comment by wangssens** [comment]
> 自动安装到系统失败，请手动安装证书。


证书安装结果什么都不弹，还是启动不了网易云
![JNKOQUSGZ~5UVYTUPHD$KZ8](https://github.com/user-attachments/assets/cc5e552b-852c-46e3-a792-d4cccf7e0bc0)

**Comment by wangssens** [comment]
> 自动安装到系统失败，请手动安装证书。

ssl安装不了，软件还是启动不了
![JNKOQUSGZ~5UVYTUPHD$KZ8](https://github.com/user-attachments/assets/c6b61df4-a699-4b80-9e5f-8eef08421a98)

**Comment by wangssens** [comment]
> 下载该文件 [SunnyNetTool.exe](https://wwxa.lanzouj.com/iNHoW28jk46f)，打开后到设置安装证书后即可。
ssl安装不了
![image](https://github.com/user-attachments/assets/7832ba74-d67d-4691-b2a2-6907fd2e4b43)

**Comment by zzl688vc** [comment]
> > 下载该文件 [SunnyNetTool.exe](https://wwxa.lanzouj.com/iNHoW28jk46f)，打开后到设置安装证书后即可。
> > ssl安装不了
> > ![图像](https://private-user-images.githubusercontent.com/105529441/367561219-7832ba74-d67d-4691-b2a2-6907fd2e4b43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzgzNzUsIm5iZiI6MTcyNjM3ODA3NSwicGF0aCI6Ii8xMDU1Mjk0NDEvMzY3NTYxMjE5LTc4MzJiYTc0LWQ2N2QtNDY5MS1iMmEyLTY5MDdmZDJlNGI0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQwNTI3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjFjNmNhNjU0MzEyMWFlZjVkYWU3ODQ3ZGFhZmY0MDY3NTkwZTk2ODE1YzAxZThlYzJjNzEwNGRmOWU2OTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BMI_Ssx8hfetj5hMxEHdg1NA0grVEBBnCtBd_QEHNa0)

你直接下载默认证书，自己导入电脑就行了

**Comment by wangssens** [comment]
> > > 下载该文件 [SunnyNetTool.exe](https://wwxa.lanzouj.com/iNHoW28jk46f)，打开后到设置安装证书后即可。
> > > ssl安装不了
> > > [![图像](https://private-user-images.githubusercontent.com/105529441/367561219-7832ba74-d67d-4691-b2a2-6907fd2e4b43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzgzNzUsIm5iZiI6MTcyNjM3ODA3NSwicGF0aCI6Ii8xMDU1Mjk0NDEvMzY3NTYxMjE5LTc4MzJiYTc0LWQ2N2QtNDY5MS1iMmEyLTY5MDdmZDJlNGI0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQwNTI3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjFjNmNhNjU0MzEyMWFlZjVkYWU3ODQ3ZGFhZmY0MDY3NTkwZTk2ODE1YzAxZThlYzJjNzEwNGRmOWU2OTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BMI_Ssx8hfetj5hMxEHdg1NA0grVEBBnCtBd_QEHNa0)](javascript:void(0))
> 
> 你直接下载默认证书，自己导入电脑就行了



> Author

11还是不可以，证书是放在这里面呀，但启动网易云还是显示我没有安装证书，重启电脑也没有效果
![image](https://github.com/user-attachments/assets/25b55e81-c23b-46d0-8296-66f04c1394c9)

**Comment by wangssens** [comment]
> 下载该文件 [SunnyNetTool.exe](https://wwxa.lanzouj.com/iNHoW28jk46f)，打开后到设置安装证书后即可。
sh手动安装证书也初始化不成功
![image](https://github.com/user-attachments/assets/c325d254-f4a6-450b-add3-a7984154df7b)
