### ISSUE TITLE
🙋 [ Question ] 简要描述，不要删除前面内容 能否定制功能

### ISSUE THREAD

**Issue by poesses** [LauZzL/leitingzhanji-ui#22]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/LauZzL/leitingzhanji-ui/issues)

请在提交问题之前回答这些问题，谢谢。 

### 你使用了哪个版本？
能否定制功能

### 出现了什么问题？
能否定制功能

### 原因分析（如果可以）
能否定制功能

### 问题重现步骤

能否定制功能

**Comment by ASCIIX** [comment]
咋了，你想定制无限钻石？
