### ISSUE TITLE
🚀 [ Feature ] 关于最新操作记录的展示方式

### ISSUE THREAD

**Issue by Shikicn** [LauZzL/leitingzhanji-ui#23]
#### 你希望增加的功能？
![1726327020425](https://github.com/user-attachments/assets/580d566e-1e8e-4b94-bba8-e3dccc777957)
希望最新的记录能在顶部显示

#### 为什么？
这样方便查看最新的操作记录

**Comment by LauZzL** [comment]
Get. 会考虑的，但还不会立即做出改变，因为在执行新的操作时会自动滚到到最新记录
