### ISSUE TITLE
📄 [ Document ] 关于购买无尽道具，最大为32767，之前用脚本测试的。

### ISSUE THREAD

**Issue by ASCIIX** [LauZzL/leitingzhanji-ui#24]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/LauZzL/leitingzhanji-ui/issues)

请在提交问题之前回答这些问题，谢谢。 

### 你使用了哪个版本？
3.0.4

### 出现了什么问题？
关于购买无尽道具，最大为32767，之前用脚本测试的。如果购买32678就变成了购买一个。

### 原因分析（如果可以）
关于购买无尽道具，最大为32767，之前用脚本测试的。如果购买32678就变成了购买一个。
也就是最大只能购买32767个。

### 问题重现步骤
关于购买无尽道具，最大为32767，之前用脚本测试的。如果购买32678就变成了购买一个。

### 截图
![QQ20240915-090809](https://github.com/user-attachments/assets/846f6e40-b885-4358-acca-dbc4f6843ba3)

**Comment by ylnlh** [comment]
购买无尽道具，还是花自己的金币，有没有刷道具的功能
