### ISSUE TITLE
🚀 [ Feature ]: Hi，能否添加这些功能？

### ISSUE THREAD

**Issue by ASCIIX** [LauZzL/leitingzhanji-ui#27]
#### 你希望增加的功能？
1. 商城一键领取10钻石，白银钥匙x1，道具x1
2. 社区一键领取20钻石
3. 星际探索免费领取。
4. 发送弹幕，领取10钻石。

#### 为什么？
1.商城道具漏领取20钻石。
2.社区奖励无法在PC上领取。
3.星际探索会少领取一次免费奖励。
4.有时候忘记领取。

请求包如下
1. 商城一键领取-----需要补齐，<font color="blue">cmdSequence，timestamp，sid，uid</font>
```json
{"head":{"cmdDataSplitLength":0,"cmdId":101,"cmdLength":0,"cmdSequence":{},"cmdVersion":4,"headVersion":0,"timestamp":{},"crcVerify":0,"platform":0,"reconnect":false,"sid":"sid","uid":"uid"},"id":1,"orderId":""}
```
2.社区领取道具请求包-----需要补齐，cmdSequence，timestamp，sid，uid
```json
{"head":{"cmdDataSplitLength":0,"cmdId":135,"cmdLength":0,"cmdSequence":{},"cmdVersion":4,"headVersion":0,"timestamp":{},"crcVerify":0,"platform":0,"reconnect":false,"sid":"sid","uid":"uid"},"actionId":1}
```
3.星际探索免费领取请求包-----需要补齐，cmdSequence，timestamp，sid，uid
```json
{"head":{"cmdDataSplitLength":0,"cmdId":88,"cmdLength":0,"cmdSequence":{},"cmdVersion":4,"headVersion":0,"timestamp":{},"crcVerify":0,"platform":0,"reconnect":false,"sid":"sid","uid":"uid"},"type":0}
```

末尾的 "type":0 是免费领取，改成type 1应该是看广告的，cmdId的88是快速探索的，87应该是右边领取的

4.发送弹幕，领取10钻石-----需要补齐，cmdSequence，timestamp，sid，uid
```json
{"head":{"cmdDataSplitLength":0,"cmdId":125,"cmdLength":0,"cmdSequence":{},"cmdVersion":4,"headVersion":0,"timestamp":{},"crcVerify":0,"platform":0,"reconnect":false,"sid":"sid","uid":"uid"},"message":"","presetMessage":"战机升空，冲锋陷阵！"}
```

**Comment by LauZzL** [comment]
他将在下个版本装配，在这之前你可以使用HTTP页面的封包功能来代替

**Comment by ASCIIX** [comment]
Hi，3.0.4版本好像没有看见在哪获取sid，uid，而且捕获数据包没有作用，在3.0.3中可以进行捕获，但是没有requests的请求包。无法获取sid，uid，能否发一份能获取sid，uid或者能捕获数据包的版本给我，谢谢！
Email：xssdhell@gmail.com

**Comment by ASCIIX** [comment]
3.0.3版本可以运行捕获，但是没有request请求包
![123](https://github.com/user-attachments/assets/a87c6056-4ed2-4ee1-81c2-5bba86ad9fdd)
![111](https://github.com/user-attachments/assets/19c9f35b-4751-43ec-a6a2-06d8d98e909e)

**Comment by LauZzL** [comment]
使用封包功能无需sid、uid，看这里：[封包编辑](https://github.com/LauZzL/leitingzhanji-ui#%E5%B0%81%E5%8C%85)，你可以使用占位符来自动替换他们

**Comment by ASCIIX** [comment]
OK，封包现在正常工作。

**Comment by wlireland353** [comment]
把电脑小程序快捷方式放到桌面，再从快捷方式启动也一样能领取20钻石，我都是这样领的
