### ISSUE TITLE
🚀 [ Feature ]: 切换一级路次级路由页面数据变为默认值

### ISSUE THREAD

**Issue by 853097424** [LauZzL/leitingzhanji-ui#28]
#### 你希望增加的功能？
希望切换列表时调过的参数能保留或者添加修改保存默认值
因以上原因，导致开启过的金币修改会回到默认值，关闭金币修改需要操作两次

#### 为什么？
当我使用闯关攻打完毕之后，需要在个人信息栏刷新并查看当前背包量
切换回闯关列表时，调过的参数回到了默认值并没有保留

**Comment by ASCIIX** [comment]
测试过，开启过的参数会保留，可以直接点击闯关食用，软件返回100是软件显示的，但是只要不是重启软件，就不会回归默认值。
![1](https://github.com/user-attachments/assets/459f8424-f5ec-4fcf-9a04-d7b6bea72146)
![2](https://github.com/user-attachments/assets/65641d6a-3cde-4949-83d8-20358eb17a6c)
![3](https://github.com/user-attachments/assets/5c7344d0-5e33-40e8-b416-f83caa99cc06)
![4](https://github.com/user-attachments/assets/62e5e946-239b-4e22-aa95-120ad2a2c9df)

**Comment by LauZzL** [comment]
将在下个版本优化显示
