### ISSUE TITLE
🐛 [ Bug ]: 用封包功能执行无尽宝箱任务时，日志显示错误

### ISSUE THREAD

**Issue by Mofan1379** [LauZzL/leitingzhanji-ui#30]
#### 您使用的版本？
网易云V3.0.4

#### 系统版本？
win11

#### 您遇到了什么问题？
用封包功能执行无尽宝箱任务时，日志显示错误，无尽的gain里，金币跟装备是用#分隔的，导致金币数量跟第1个装备的id打印到一起了，第1个装备也无法正常打印出来，5个装备只能打印后4个

#### 请提供错误截图？
![Snipaste_2024-09-16_15-24-15](https://github.com/user-attachments/assets/e8257568-f7fe-4006-a5e7-55d1dbe82483)
![Snipaste_2024-09-16_15-25-27](https://github.com/user-attachments/assets/7760d057-7c1e-4047-83cf-880376006209)

**Comment by LauZzL** [comment]
将在下个版本修复
