### ISSUE TITLE
🐛 [ Bug ]: 每日广告体力X1次

### ISSUE THREAD

**Issue by wlireland353** [LauZzL/leitingzhanji-ui#31]
#### 您使用的版本？
3.0.5

#### 系统版本？
windows 11

#### 您遇到了什么问题？
每日广告体力X1次，点击后连续领取了4次

#### 请提供错误截图？
![1726507236420](https://github.com/user-attachments/assets/b49ae055-5141-425c-9f99-9db9d6de104b)

**Comment by 853097424** [comment]
显示问题，X1和x4对换了

**Comment by LauZzL** [comment]
删除程序目录下的Cache文件夹，重启即可
