### ISSUE TITLE
🚀 [ Feature ]: 增加闯关结算时双倍可选选项（或自动判断是否还有剩余双倍结算次数）

### ISSUE THREAD

**Issue by sodadoss** [LauZzL/leitingzhanji-ui#32]
#### 你希望增加的功能？
以复选框的形式，在功能模块-闯关选项卡中，增设双倍结算复选框，即可自主决定是否以双倍方式结算

#### 为什么？
目前的程序在闯关关卡结算时，好像默认是以双倍方式结算的。
然而，每天的双倍结算有次数限制，超过这个次数后，好像就会出现如下的提示

> 双倍领取失败：与莉莎的通信似乎受到了星盟的干扰，请尝试更换通信频道

这里如果改为自主决定是否以双倍方式结算，就可以避免出现这个问题。另一种方式是通过判断当前是否还有剩余双倍次数来自动选择，不过这样显然要更复杂一些。

**Comment by LauZzL** [comment]
在这里设置：闯关-其他-3经验双倍

**Comment by sodadoss** [comment]
`闯关`-`其他`-`3经验双倍`这里我没有勾选（即默认状态），但还是会出现`双倍领取失败：与莉莎的通信似乎受到了星盟的干扰，请尝试更换通信频道`，是其他哪个地方也需要调整吗

**Comment by LauZzL** [comment]
尝试勾选后再取消勾选，我们可能漏掉了他的默认值处理，将在下个版本中修复

**Comment by wlireland353** [comment]
默认是选择了双倍的，需要先勾上，再取消
