### ISSUE TITLE
🐛 [ Bug ]: 无法成功捕获数据

### ISSUE THREAD

**Issue by sodadoss** [LauZzL/leitingzhanji-ui#33]
#### 您使用的版本？
3.0.5

#### 系统版本？
win10 22H2

#### 您遇到了什么问题？
勾选“捕获数据”后，在小程序页面执行操作（如手动完成一次闯关模式），没有产生任何记录。

其他功能使用正常。

已尝试：重启小程序、重启本程序，均无法解决问题。

#### 请提供错误截图？
![image](https://github.com/user-attachments/assets/d2bfb711-069e-4acd-a3be-59289e9f7612)

**Comment by LauZzL** [comment]
暂时禁用了他。我们在对他进行重构，以更良好的方式来展示，而不局限于请求体。
