### ISSUE TITLE
🐛 [ Bug ]: 2个boss残骸经验道具会消耗3经验双倍的次数

### ISSUE THREAD

**Issue by mantianxiang** [LauZzL/leitingzhanji-ui#36]
#### 请提供错误截图？
<img width="686" alt="081bccc427bbc959bccb5bbdfe4bef8" src="https://github.com/user-attachments/assets/59fb0b9c-37d9-495d-a730-2bca72bb00f0">

**Comment by LauZzL** [comment]
在下个版本中修复
