### ISSUE TITLE
🚀 [ Feature ]: 作者，可不可以重新加个去广告？

### ISSUE THREAD

**Issue by wlireland353** [LauZzL/leitingzhanji-ui#37]
#### 你希望增加的功能？
去广告/免广告

#### 为什么？
总有个别情况下需要看广告，比如24小时一个白银箱子广告，打无尽时老早被导弹炸死可以复活一次继续刷箱子

**Comment by LauZzL** [comment]
将在下个版本装配

**Comment by LauZzL** [comment]
我们已经修复了这个错误，请将版本更新至最新版本

**Comment by XO9527** [comment]
为什么勾选了英雄难度还是打的普通

**Comment by sarilang88** [comment]
畅玩卡该怎么使用啊 点了没效果
