### ISSUE TITLE
今天下午官方在服务器端更新了，功能用不了非软件bug

### ISSUE THREAD

**Issue by Mofan1379** [LauZzL/leitingzhanji-ui#4]
#### 您使用的版本？
网易云V3

#### 系统版本？
windows11

#### 您遇到了什么问题？
今天下午官方在服务器端更新了，加了验证，所以闯关，无尽宝箱，boss，活动关都打不了，只有光辉可以打，不是软件本身的bug，是官方更新验证了

**Comment by LauZzL** [comment]
你是对的，但是我们已在下个版本中修复了该问题，我们需要时间来验证他，他将在明天发布不出意外的话。

**Comment by LauZzL** [comment]
[v3.0.1](https://github.com/LauZzL/leitingzhanji-ui/releases/tag/v3.0.1)
