### ISSUE TITLE
🐛 [ Bug ]: HTTP功能区，“运行”功能区，点击运行按钮没效果

### ISSUE THREAD

**Issue by Mofan1379** [LauZzL/leitingzhanji-ui#43]
#### 您使用的版本？
网易云V3.0.7

#### 系统版本？
win11

#### 您遇到了什么问题？
HTTP功能区，“运行”功能区，点击运行按钮没效果，点了之后不会运行封包，要在“封包”功能区，导入之后点执行才能运行封包，是设计如此还是bug？

#### 请提供错误截图？
![Snipaste_2024-09-24_22-59-31](https://github.com/user-attachments/assets/0cf42e3b-c372-4439-a8cd-22fb4b552370)

**Comment by LauZzL** [comment]
这是一个BUG，我们遗漏了这个分支处理，他将在下个版本修复。
在`运行`页你可以执行任意封包，在`封包`页你只能导入和调试`允许编辑`的封包

**Comment by ylnlh** [comment]
这个封包我没搞太明白，是把我的操作步骤记录下来，以后一键执行吗，这个捕获数据我勾选了，怎么才能捕获到，面板还是空，文档操作步骤太少了，需要自己摸索

**Comment by LauZzL** [comment]
> 这个封包我没搞太明白，是把我的操作步骤记录下来，以后一键执行吗，这个捕获数据我勾选了，怎么才能捕获到，面板还是空，文档操作步骤太少了，需要自己摸索

捕获数据将在下个版本中更新，同时我们会编写一个文档来提供说明。
look this: #46
