### ISSUE TITLE
🐛 [ Bug ]: Hi，HTTP封包 UI 可否能固定下面的输出框和上面的执行，封包，运行，只让中间移动？

### ISSUE THREAD

**Issue by ASCIIX** [LauZzL/leitingzhanji-ui#44]
#### 您使用的版本？
3.0.7

#### 系统版本？
Windows 10 22H2 19045.3208

#### 您遇到了什么问题？
HTTP封包 UI 中，当步骤较多时，需要移动滚动条，当移动滚动条到最底下时，上面执行按钮就无法点击，需要再次移动到最上面，相反，点击执行后，我想查看输出内容，需要移动到最下面，执行结束后，又需要返回到最上面，点执行。

#### 请提供错误截图？
![1233](https://github.com/user-attachments/assets/5e641314-9042-4ad0-8e5b-ccf9213ae55c)
![23811](https://github.com/user-attachments/assets/895f6a89-6d29-4138-a196-8a4a4f6dc257)

**Comment by LauZzL** [comment]
我们注意到了这个问题，他将在今晚进行动态更新，当你收到通知时，请删除程序目录中的`Cache`文件重启程序即可。

**Comment by ASCIIX** [comment]
OK，Thank u

**Comment by LauZzL** [comment]
已更新 删除Cache重新运行程序即可

**Comment by ASCIIX** [comment]
还是会有bug，输出框重叠了。

![2338](https://github.com/user-attachments/assets/5da0fa38-5c2d-432d-8ef2-b71e90da266f)
