### ISSUE TITLE
🚀 [ Feature ]: Hi，HTTP封包 UI 可否能增加一个循环步骤，或者复制步骤的按钮，或者移动步骤的？

### ISSUE THREAD

**Issue by ASCIIX** [LauZzL/leitingzhanji-ui#45]
#### 你希望增加的功能？
HTTP封包 UI 可否能增加一个循环步骤，或者复制步骤的按钮，或者移动步骤的？

#### 为什么？
1. 希望能增加一个复制封包，或者循环执行的，例如我有150个步骤，其中15个为一组，我想加个循环执行10次，而不想复制150个封包步骤，这样太繁琐了。
2. 而且加错一个或者误删中间一个，就需要从这个封包的第几组重新加。

**Comment by LauZzL** [comment]
查看该issue：[[ Feature ]: 封包功能升级与优化](https://github.com/LauZzL/leitingzhanji-ui/issues/46)
