### ISSUE TITLE
🚀 [ Feature ]: 关于攻打海盗宝箱

### ISSUE THREAD

**Issue by zyc592** [LauZzL/leitingzhanji-ui#47]
怎么操作、设置才能结算啊 
有会的大佬告诉一下    
![微信截图_20240925153139](https://github.com/user-attachments/assets/739e0036-2c79-4a15-9a9b-af58f75449b1)
谢谢

**Comment by 853097424** [comment]
150,time

**Comment by ASCIIX** [comment]
请看#49食用，[#49 ](https://github.com/LauZzL/leitingzhanji-ui/issues/49)

**Comment by zyc592** [comment]
> 请看#49食用，[#49 ](https://github.com/LauZzL/leitingzhanji-ui/issues/49)

感谢

**Comment by zyc592** [comment]
> 150,time

我试了 不行 结算不了  是因为战力的原因吗我10843战力

**Comment by ASCIIX** [comment]
> > 150,time
> 
> 我试了 不行 结算不了 是因为战力的原因吗我10843战力

可能服务器存在验证，请使用封包功能执行。
