### ISSUE TITLE
📚 [ Docs ]: 关于攻打海盗宝箱，以及快速刷取。

### ISSUE THREAD

**Issue by ASCIIX** [LauZzL/leitingzhanji-ui#49]
### 哪个版本？
3.0.7

### 补充
1. 请使用HTTP封包功能
2. 添加2个步骤，步骤代码如下，不会使用禁止修改任何数值。
3. 初始化之后，点击执行即可，秒结算，无需等待，需要灰烬，圣光，冲刺，3个道具。

发送无尽开始包，需要道具版本，搭配结束包使用。
已修复，和实装。防止有人。

发送无尽开始包，不需要道具版本，搭配结束包使用，有概率失败。
已修复，和实装。防止有人。

发送无尽结算包
已修复，和实装。防止有人。

### 截图 (如果可以)
已修复，和实装。防止有人。

**Comment by ASCIIX** [comment]
任意一个开始包即可，一个开始包搭配一个结束包

**Comment by ylnlh** [comment]
PVP能封包吗，无尽匹配会有对手，这个可以吗？你这个封包数据里面有些关键字段能解释一下吗，包含无尽宝箱吗？

**Comment by ASCIIX** [comment]
可以实现，但是不公开

**Comment by zixiwangluo** [comment]
> 可以实现，但是不公开

作者你好，非常感谢你提供了这个十分方便的封包
我有一个小请求，如果可以的话，是否方便开发一个快速刷取无尽随机装备宝箱（一局4个or5个宝箱）的封包呢？在软件内运行无尽的话，需要等待的时间过于久了一些。
