### ISSUE TITLE
🐛 [ Bug ]: HTTP封包无法捕获数据，以及js-hook无法调用。

### ISSUE THREAD

**Issue by ASCIIX** [LauZzL/leitingzhanji-ui#50]
#### 您使用的版本？
3.0.7

#### 系统版本？
Windows 10 22H2 19045.3208

#### 您遇到了什么问题？
1. HTTP封包无法捕获数据。
2. js-hook无法调用。

#### 请提供错误截图？
![113857](https://github.com/user-attachments/assets/cc2e0aeb-2039-42df-9bad-658f75821b35)

**Comment by LauZzL** [comment]
这不是一个BUG，他在下个版本更新中才会实装

**Comment by ASCIIX** [comment]
噢噢
