### ISSUE TITLE
🚀 [ Feature ]: 希望增加一个邀请好友1000人的功能

### ISSUE THREAD

**Issue by iLinglingling** [LauZzL/leitingzhanji-ui#51]
#### 你希望增加的功能？
希望增加一个邀请好友1000人的功能

#### 为什么？
每天可以领50钻石，3*9600经验。手动很难邀请1000人。
![1727333593928](https://github.com/user-attachments/assets/a3386fc1-b462-4c95-894a-75a920bc505e)

**Comment by iLinglingling** [comment]
> 不太现实

因为我看到有其他开发者实现了这个功能

**Comment by LauZzL** [comment]
> 因为我看到有其他开发者实现了这个功能

我会将他添加到清单中，但不会在下个版本中。

**Comment by mao051200** [comment]
这个功能可以有
