### ISSUE TITLE
🚀 [ Feature ]: 英雄难度的关卡

### ISSUE THREAD

**Issue by MOUXIU111** [LauZzL/leitingzhanji-ui#54]

**Comment by LauZzL** [comment]
我们现在的工作量有点多，暂时没有时间去添加新的关卡功能，他可能要比预想中来的更晚。

如果能为我们提供封包数据，他将很快装配。

**Comment by ASCIIX** [comment]
大佬大佬，看一下vk

**Comment by LauZzL** [comment]
下载预发布版本：[Releases](https://github.com/LauZzL/leitingzhanji-ui/releases)
