### ISSUE TITLE
🐛 [ Bug ]: 攻打材料点击没反应，是否有特殊触发条件

### ISSUE THREAD

**Issue by maple2623** [LauZzL/leitingzhanji-ui#55]
#### 您使用的版本？
LTZJ-NEM.Build.3.0.7

#### 系统版本？
Win11

#### 您遇到了什么问题？
攻打材料点击没反应

#### 请提供错误截图？
![image](https://github.com/user-attachments/assets/e6194267-b81e-4101-a133-d94cfa8598af)

**Comment by LauZzL** [comment]
Get. 我又忘了他的处理分支，将在下个版本修复，你可以暂时使用规则来代替。
