### ISSUE TITLE
闯关模式还是没法使用

### ISSUE THREAD

**Issue by wlireland353** [LauZzL/leitingzhanji-ui#6]
#### 您使用的版本？
3.0.1
#### 系统版本？
Windows11

#### 您遇到了什么问题？
闯关模式下的【攻打】失效，【材料，自定义】这二项功能点击攻打后没有反应，日志也没有

#### 请提供错误截图？
![1726112248629](https://github.com/user-attachments/assets/5cf97308-56bc-4001-a6bc-6caf1099e81e)

**Comment by LauZzL** [comment]
多尝试几次

![image](https://github.com/user-attachments/assets/1fd9773f-9bc0-4832-996f-2a2689ff40ac)

**Comment by Rx1314** [comment]
很好奇，到底更新了个什么验证，就离谱的很

**Comment by wlireland353** [comment]
> 多尝试几次
> 
> ![图像](https://private-user-images.githubusercontent.com/89786902/366712640-1fd9773f-9bc0-4832-996f-2a2689ff40ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMTQ3NTEsIm5iZiI6MTcyNjExNDQ1MSwicGF0aCI6Ii84OTc4NjkwMi8zNjY3MTI2NDAtMWZkOTc3M2YtOWJjMC00ODMyLTk5NmYtMmEyNjg5ZmY0MGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA0MTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMjQ3NTgxNGY0NGU0MDc0Mjc4NDFjM2Y5MDUyMGQ5OTFhMTlhNDlhYWRmYTgyODljMjA3M2MzMjJmNzM0ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rMopdOTjQlBpk4QGUV1QehqrirDiIe4-lMaYmbzgztc)

依旧不行，我还以为是没开防检测的原因，特地开启了防检测和关闭经验双倍，但是攻打多次依然显示失败

**Comment by LauZzL** [comment]
> 
> 依旧不行，我还以为是没开防检测的原因，特地开启了防检测和关闭经验双倍，但是攻打多次依然显示失败

提供一下大概战斗力

**Comment by wlireland353** [comment]
> > 依旧不行，我还以为是没开防检测的原因，特地开启了防检测和关闭经验双倍，但是攻打多次依然显示失败
> 
> 提供一下大概战斗力

战力14320
