### ISSUE TITLE
🚀 [ Feature ]:请教大佬安装问题，非专业人士想要使用好难

### ISSUE THREAD

**Issue by nging888** [LauZzL/leitingzhanji-ui#60]

**Comment by NorthYH** [comment]
你可以问详细一点，首先不能在压缩包里运行，第二解压后的路径不要有中文，最后windows 7用户需要下载 `Webview2`才可以使用。

**Comment by MOUXIU111** [comment]
比如我想把[增加英雄难度、战神材料]的功能添加3.0.7版本，这是否可以做到

**Comment by LauZzL** [comment]
[使用文档](https://lauzzl.github.io/leitingzhanji-docs/)

**Comment by LauZzL** [comment]
> 感谢大佬的回复，具体情况是下载并解压了3.0.7版本下第一个压缩包，运行exe程序直接闪退。是因为缺少框架的问题吗，系统为win10

尝试安装 Webview2

**Comment by AdaJoker** [comment]
> [使用文档](https://lauzzl.github.io/leitingzhanji-docs/)

大佬，咋登录啊，没找到登录模块
