### ISSUE TITLE
🚀 [ Feature ]: 开放数值修改，英雄闯关双倍

### ISSUE THREAD

**Issue by ylnlh** [LauZzL/leitingzhanji-ui#61]
#### 你希望增加的功能？
1.放开数值修改
2.英雄闯关双倍材料

#### 为什么？
非氪金玩家闯关打不上去，虽然后续有js-hook，但是还是血书目前放开数值修改，不然进度会落后很多
非氪金玩家英雄闯关无法打两次

放开数值修改

**Comment by winsorwins** [comment]
建议+1

**Comment by winsorwins** [comment]
> #### 你希望增加的功能？
> 1.放开数值修改 2.英雄闯关双倍材料
> 
> #### 为什么？
> 非氪金玩家闯关打不上去，虽然后续有js-hook，但是还是血书目前放开数值修改，不然进度会落后很多 非氪金玩家英雄闯关无法打两次
> 
> 放开数值修改

+1

**Comment by winsorwins** [comment]
支持开放数据修改功能

**Comment by LauZzL** [comment]
下载预发布版本：[Releases](https://github.com/LauZzL/leitingzhanji-ui/releases)

**Comment by ASCIIX** [comment]
> #### 你希望增加的功能？
> 1.放开数值修改 2.英雄闯关双倍材料
> 
> #### 为什么？
> 非氪金玩家闯关打不上去，虽然后续有js-hook，但是还是血书目前放开数值修改，不然进度会落后很多 非氪金玩家英雄闯关无法打两次
> 
> 放开数值修改

我怀疑你想上天，英雄关卡都没广告，怎么给你双倍，你去找无尽海盗打一架，看看他会不会给你双倍。

**Comment by ylnlh** [comment]
![image](https://github.com/user-attachments/assets/08fccfde-31ae-48a4-8156-7b9a5c435ca3)
英雄模式24关失败了

**Comment by ASCIIX** [comment]
24关特殊一点。

**Comment by LauZzL** [comment]
>  英雄模式24关失败了

下个版本修复 打的真快牢弟

**Comment by ylnlh** [comment]
这个打闯关有封号的风险不，就是肝，分币不充，所以资源越多越好，版本测试工程师就是我们，测试都不需要了

**Comment by LauZzL** [comment]
> 这个打闯关有封号的风险不，就是肝，分币不充，所以资源越多越好，版本测试工程师就是我们，测试都不需要了

暂时没有出现过案例 你都用上第三方工具了 就不要考虑封号风险了
