### ISSUE TITLE
🐛 [ Bug ]: 进游戏就被检测了

### ISSUE THREAD

**Issue by shuini01** [LauZzL/leitingzhanji-ui#62]
#### 您使用的版本？
3.0.8

#### 系统版本？
win11

#### 您遇到了什么问题？
进游戏就被检测了

#### 请提供错误截图？
![01](https://github.com/user-attachments/assets/8460e900-3e1c-49cc-b790-49168a64dfff)

**Comment by Mofan1379** [comment]
关闭月卡功能就不会了

**Comment by shuini01** [comment]
> 关闭月卡功能就不会了

ok
