### ISSUE TITLE
🐛 [ Bug ]: 初始化失败

### ISSUE THREAD

**Issue by WaitFme** [LauZzL/leitingzhanji-ui#63]
#### 您使用的版本？
3.0.8pre

#### 系统版本？
Windows11-26100.1742

#### 您遇到了什么问题？
点击初始化提示初始化失败。

#### 请提供错误截图？
![image](https://github.com/user-attachments/assets/821f79bb-408b-4044-92b7-fd6b63a0a260)

**Comment by LauZzL** [comment]
关闭windows防火墙 或放行2022端口

**Comment by WaitFme** [comment]
已解决，放行端口后还得重启一下。
