### ISSUE TITLE
🚀 [ Feature ]: 小白很难受，不知道怎么登录，没找到登录的地方

### ISSUE THREAD

**Issue by AdaJoker** [LauZzL/leitingzhanji-ui#69]
#### 你希望增加的功能？
更加简洁的登录方式

#### 为什么？
![image](https://github.com/user-attachments/assets/3d533d80-82a8-4f9c-bb83-e97b103b168a)

**Comment by Mofan1379** [comment]
自带的功能够多了，基本不需要用到封包

**Comment by LauZzL** [comment]
不清楚你在说什么，程序没有登录功能，扩展封包不是给小白用的

**Comment by AdaJoker** [comment]
> 自带的功能够多了，基本不需要用到封包

是的，我指的是怎么登录账号，我太菜了，不知道怎么使用

**Comment by LauZzL** [comment]
> 是的，我指的是怎么登录账号，我太菜了，不知道怎么使用

查看文档
