### ISSUE TITLE
🐛 [ Bug ]: 点击获取战神材料的时候会报错

### ISSUE THREAD

**Issue by AdaJoker** [LauZzL/leitingzhanji-ui#75]
#### 您使用的版本？
3.09

#### 系统版本？
win10

#### 您遇到了什么问题？
点击获取战神材料的时候，会报错，点击确定就直接退出程序了

#### 请提供错误截图？
![image](https://github.com/user-attachments/assets/a59b8be2-faca-40b8-9cd3-134e4caa3bd5)

**Comment by LauZzL** [comment]
使用自定义，材料忘记弄了，下个版本修复
