### ISSUE TITLE
🐛 [ Bug ]: bossb模式攻打失败

### ISSUE THREAD

**Issue by Harbin-chenguanxi** [LauZzL/leitingzhanji-ui#77]
#### 您使用的版本？

3.0.9
#### 系统版本？
win10

#### 您遇到了什么问题？
bossb模式攻打失败

#### 请提供错误截图？
![Uploading 屏幕截图(8)(1).png…]()

**Comment by LauZzL** [comment]
无法看到你提供的截图，在描述问题时请详细一点

**Comment by Harbin-chenguanxi** [comment]
这个是截图，还有我的金币被清零 现在只要使用闯关功能就会被清零 这个怎么解决呀[
![Uploading 屏幕截图(8)(1).png…]()
](url)

**Comment by LauZzL** [comment]
看到不你的截图 暂时没遇到过清0的情况 如果你开启了金币修改就关闭后重试
