### ISSUE TITLE
🐛 [ Bug ]: pvp功能

### ISSUE THREAD

**Issue by wlireland353** [LauZzL/leitingzhanji-ui#82]
#### 您使用的版本？
3.1.0

#### 系统版本？
windows 11

#### 您遇到了什么问题？
pvp问题：
1，无论匹不匹配到对手，都会显示匹配未成功，然后计算为1次攻打，这样的话次数设计好像作用不大了
2，匹配到对手后，需要重启小程序才能进行下一次攻打，不知道有没有办法优化，否则操作有点繁琐。

**Comment by Azz-AI** [comment]
这是因为黑号了，匹配不到对手，被官方制裁了

**Comment by wlireland353** [comment]
> 这是因为黑号了，匹配不到对手，被官方制裁了

不是黑号，显示未匹配成功和关卡攻打完成，但其实匹配成功了，因为再次攻打会显示《与莉莎的通信似乎受到了星盟的干扰》，重启小程序后才看到有新的对战记录

**Comment by LauZzL** [comment]
1. 次数是进行匹配几次 而不是成功几次 如果设计为判断成功 你是黑号的话 就不会成功 那就会导致程序陷入死循环一直匹配
2. 这个是数据判断有问题 我的号打不了匹配 下个版本会修复

暂时可以使用JavaScript扩展来完成PVP或使用封包完成PVP

**Comment by wlireland353** [comment]
> 1. 次数是进行匹配几次 而不是成功几次 如果设计为判断成功 你是黑号的话 就不会成功 那就会导致程序陷入死循环一直匹配
> 2. 这个是数据判断有问题 我的号打不了匹配 下个版本会修复
> 
> 暂时可以使用JavaScript扩展来完成PVP或使用封包完成PVP


好的，感谢大佬！！

**Comment by wlireland353** [comment]
> 1. 次数是进行匹配几次 而不是成功几次 如果设计为判断成功 你是黑号的话 就不会成功 那就会导致程序陷入死循环一直匹配
> 2. 这个是数据判断有问题 我的号打不了匹配 下个版本会修复
> 
> 暂时可以使用JavaScript扩展来完成PVP或使用封包完成PVP

大佬，今天凌晨我打pvp，发现匹配成功，但是不加挑战币，是因为没有扣体力的原因吗？ 金币是扣掉2000了的

**Comment by Mofan1379** [comment]
> 1. 次数是进行匹配几次 而不是成功几次 如果设计为判断成功 你是黑号的话 就不会成功 那就会导致程序陷入死循环一直匹配
> 2. 这个是数据判断有问题 我的号打不了匹配 下个版本会修复
> 
> 暂时可以使用JavaScript扩展来完成PVP或使用封包完成PVP



> 1. 次数是进行匹配几次 而不是成功几次 如果设计为判断成功 你是黑号的话 就不会成功 那就会导致程序陷入死循环一直匹配
> 2. 这个是数据判断有问题 我的号打不了匹配 下个版本会修复
> 
> 暂时可以使用JavaScript扩展来完成PVP或使用封包完成PVP

可以再添加一个成功几次则停止匹配的参数，该参数必须<匹配次数，当匹配成功次数达到该参数时，停止匹配

**Comment by Mofan1379** [comment]
> 1. 次数是进行匹配几次 而不是成功几次 如果设计为判断成功 你是黑号的话 就不会成功 那就会导致程序陷入死循环一直匹配
> 2. 这个是数据判断有问题 我的号打不了匹配 下个版本会修复
> 
> 暂时可以使用JavaScript扩展来完成PVP或使用封包完成PVP

可以再添加一个成功几次则停止匹配的参数，该参数必须<匹配次数，当匹配成功次数达到该参数时，停止匹配

**Comment by Mofan1379** [comment]
> 1. 次数是进行匹配几次 而不是成功几次 如果设计为判断成功 你是黑号的话 就不会成功 那就会导致程序陷入死循环一直匹配
> 2. 这个是数据判断有问题 我的号打不了匹配 下个版本会修复
> 
> 暂时可以使用JavaScript扩展来完成PVP或使用封包完成PVP

可以再添加一个成功几次则停止匹配的参数，该参数必须 ≤ 匹配次数，当匹配成功次数达到该参数时，停止匹配

**Comment by ASCIIX** [comment]
> > 1. 次数是进行匹配几次 而不是成功几次 如果设计为判断成功 你是黑号的话 就不会成功 那就会导致程序陷入死循环一直匹配
> > 2. 这个是数据判断有问题 我的号打不了匹配 下个版本会修复
> > 
> > 暂时可以使用JavaScript扩展来完成PVP或使用封包完成PVP
> 
> 可以再添加一个成功几次则停止匹配的参数，该参数必须 ≤ 匹配次数，当匹配成功次数达到该参数时，停止匹配

没有必要，已经设置攻打几次了，达到就会停止。

**Comment by ylnlh** [comment]
开挂打英雄24，现在最高战力是打不过的，官方只要数据库一个sql就能搜索出全部开挂玩家，为啥不会被封？是因为闯关模式发送的包合规吗

**Comment by ASCIIX** [comment]
> 开挂打英雄24，现在最高战力是打不过的，官方只要数据库一个sql就能搜索出全部开挂玩家，为啥不会被封？是因为闯关模式发送的包合规吗

你看96关的封了多少，封号他还有多少日活？你都开了，还怕封号？

**Comment by ylnlh** [comment]
我是不怕，只是想看看官方是哪种态度，我在想我打96发送的数据包都通过检测了，他也没理由封呀
