### ISSUE TITLE
🤔 [ Question ]: 一进游戏金币就被清零 是被封了吗不开辅助也是 只要一使用金币 就显示重新登陆  然后就金币清零

### ISSUE THREAD

**Issue by Harbin-chenguanxi** [LauZzL/leitingzhanji-ui#84]

**Comment by Mofan1379** [comment]
你小子是不是刷金币刷过头了？刷超过了21亿金币，超出int整型，变为负值了

**Comment by Harbin-chenguanxi** [comment]
18亿吧没到21呀

**Comment by Mofan1379** [comment]
> 18亿吧没到21呀

![Snipaste_2024-09-29_18-55-48](https://github.com/user-attachments/assets/ccd0672c-d47f-4221-ba10-3ce9697363d6)
打开这个界面看一下不就知道了，刷到负值就继续刷21亿金币就能够回正了

**Comment by Harbin-chenguanxi** [comment]
神医  确实是负数了 预计明天刷回来

**Comment by ASCIIX** [comment]
> 神医 确实是负数了 预计明天刷回来

建议把背包留位置，小型敌机残骸赶紧卖，不然明天占空间，啥也干不了。之前爆了一次，

**Comment by 142857-xz** [comment]
原来有上限，我昨天也爆了
