### ISSUE TITLE
🚀 [ Feature ]: 能不能加一个固定双倍按钮

### ISSUE THREAD

**Issue by MOUXIU111** [LauZzL/leitingzhanji-ui#85]

**Comment by wlireland353** [comment]
嗯，希望增加一个固定双倍，不管掉落几个经验都能生效

**Comment by ASCIIX** [comment]
暂时可以使用封包来。
Eg：先攻打战神关卡，然后在使用封包。
![92229](https://github.com/user-attachments/assets/b7ba697d-0928-4528-a726-e659983f07ca)
![92255](https://github.com/user-attachments/assets/13c496d3-b77c-4178-a0cf-ab51c63874ea)

双倍数据包
```json
{"head":{"cmdDataSplitLength":0,"cmdId":118,"cmdLength":0,"cmdSequence":"{cmdSequence}","cmdVersion":4,"headVersion":0,"timestamp":"{timestamp}","crcVerify":0,"platform":0,"reconnect":false,"sid":"{sid}","uid":"{uid}"}}
```

**Comment by LauZzL** [comment]
双倍在英雄关卡是可以使用的 下个版本会增加非3经验时也双倍的选项
