### ISSUE TITLE
🐛 [ Bug ]: 幸运转盘疑似无效？

### ISSUE THREAD

**Issue by ASCIIX** [LauZzL/leitingzhanji-ui#87]
#### 您使用的版本？
3.1.1

#### 系统版本？
Windows 10 22H2 19045.3208

#### 您遇到了什么问题？
幸运转盘疑似无效果？不只是免费抽奖的。

#### 请提供错误截图？
![3537](https://github.com/user-attachments/assets/477b1290-2d1c-430d-8494-97611972d0b7)

![93615](https://github.com/user-attachments/assets/9108dcd3-83d2-43ee-ad3a-0ba3cd73ddd7)

幸运转盘
```json
{"head":{"cmdDataSplitLength":0,"cmdId":64,"cmdLength":0,"cmdSequence":"{cmdSequence}","cmdVersion":4,"headVersion":0,"timestamp":"{timestamp}","crcVerify":0,"platform":0,"reconnect":false,"sid":"{sid}","uid":"{uid}"}}
```

**Comment by LauZzL** [comment]
done
