### ISSUE TITLE
🚀 [ Feature ]: 能否增加一个一键抽10次幸运转盘的功能

### ISSUE THREAD

**Issue by FunnyMudChouPee** [LauZzL/leitingzhanji-ui#88]
#### 你希望增加的功能？
请问能否增加一个一键抽10次幸运转盘的功能

#### 为什么？
因为遇到想要的光辉或者是道具一个一个点要点10下，还等等动画转完就很麻烦，谢谢

**Comment by ASCIIX** [comment]
自己点10次幸运抽奖即可，暂时没有一键10次的封包。

**Comment by Mofan1379** [comment]
用网易云的幸运转盘功能即可，不用等动画
