### ISSUE TITLE
🐛 [ Bug ]: 双倍领取失败

### ISSUE THREAD

**Issue by wlireland353** [LauZzL/leitingzhanji-ui#89]
#### 您使用的版本？
3.1.2

#### 系统版本？
windows 11

#### 您遇到了什么问题？
双倍领取失败：凌晨打了战神关卡，勾选了双倍【任何情况】没有效果，刚才手动去扫荡时才发现还有5次双倍机会

#### 请提供错误截图？
![1727642417495](https://github.com/user-attachments/assets/c7810c7b-d767-434d-a6df-836a802f8f45)

**Comment by ASCIIX** [comment]
战神代码更改了，等待修复

**Comment by ASCIIX** [comment]
如果急用，请攻打完战神，使用封包功能，添加步骤，发送下面这个数据包。

```json
{"head":{"cmdDataSplitLength":0,"cmdId":118,"cmdLength":0,"cmdSequence":"{cmdSequence}","cmdVersion":4,"headVersion":0,"timestamp":"{timestamp}","crcVerify":0,"platform":0,"reconnect":false,"sid":"{sid}","uid":"{uid}"},"mode":3}
```

**Comment by ASCIIX** [comment]
都放假了，就让作者歇会吧😅

**Comment by wlireland353** [comment]
> 如果急用，请攻打完战神，使用封包功能，添加步骤，发送下面这个数据包。
> 
> ```json
> {"head":{"cmdDataSplitLength":0,"cmdId":118,"cmdLength":0,"cmdSequence":"{cmdSequence}","cmdVersion":4,"headVersion":0,"timestamp":"{timestamp}","crcVerify":0,"platform":0,"reconnect":false,"sid":"{sid}","uid":"{uid}"},"mode":3}
> ```

嗯，好的，我试试，问题不大，不行扫荡也能领取

**Comment by ASCIIX** [comment]
测试过了，一共可以领10次，普通5次，炼狱5次，炼狱用上面的，这个也可用
```json
{"head":{"cmdDataSplitLength":0,"cmdId":118,"cmdLength":0,"cmdSequence":"{cmdSequence}","cmdVersion":4,"headVersion":0,"timestamp":"{timestamp}","crcVerify":0,"platform":0,"reconnect":false,"sid":"{sid}","uid":"{uid}"}}
```

**Comment by wlireland353** [comment]
> 测试过了，一共可以领10次，普通5次，炼狱5次，炼狱用上面的，这个也可用
> 
> ```json
> {"head":{"cmdDataSplitLength":0,"cmdId":118,"cmdLength":0,"cmdSequence":"{cmdSequence}","cmdVersion":4,"headVersion":0,"timestamp":"{timestamp}","crcVerify":0,"platform":0,"reconnect":false,"sid":"{sid}","uid":"{uid}"}}
> ```
好的，感谢，今晚我测试一下

**Comment by LauZzL** [comment]
在下个版本修复

**Comment by sodadoss** [comment]
刚刚更新的3.1.3还存在这个问题，不过是普通难度关卡，在有双倍次数的情况下，勾选“任何情况”，提示“双倍领取失败：与莉莎的通信似乎受到了星盟的干扰，请尝试更换通信频道”。

英雄难度的没有测试。

**Comment by ASCIIX** [comment]
> 刚刚更新的3.1.3还存在这个问题，不过是普通难度关卡，在有双倍次数的情况下，勾选“任何情况”，提示“双倍领取失败：与莉莎的通信似乎受到了星盟的干扰，请尝试更换通信频道”。
> 
> 英雄难度的没有测试。

我这边没问题，看一下是不是背包满了。

**Comment by sodadoss** [comment]
> > 刚刚更新的3.1.3还存在这个问题，不过是普通难度关卡，在有双倍次数的情况下，勾选“任何情况”，提示“双倍领取失败：与莉莎的通信似乎受到了星盟的干扰，请尝试更换通信频道”。
> > 英雄难度的没有测试。
> 
> 我这边没问题，看一下是不是背包满了。

背包没有满，手动扫荡领取双倍是正常的，我明天再试一下吧。

**Comment by sodadoss** [comment]
我昨天遇到的普通关卡双倍领取失败的原因应该是如 #92 所述的那样，普通关卡双倍领取消耗的是英雄关卡的次数。昨天我是先手动完成的5次英雄双倍，所以再通过程序获取普通关卡双倍时会因为没有次数而失败。今天又测试了一下，普通关卡双倍的确消耗的是英雄双倍的次数。
