### ISSUE TITLE
无尽问题

### ISSUE THREAD

**Issue by TYUST-HEIBAIHUI** [LauZzL/leitingzhanji-ui#9]
#### 您使用的版本？
3.0.1

#### 系统版本？
windows11

#### 您遇到了什么问题？
无尽模式无法使用

#### 请提供错误
![6f029dec93bc76784901adde29fabe7](https://github.com/user-attachments/assets/4de3417a-2291-4e1f-abfc-6a7015b9804f)
截图？

**Comment by LauZzL** [comment]
宝箱可能超出了，可以尝试HTTP替换规则

**Comment by TYUST-HEIBAIHUI** [comment]
感谢作者大大
![image](https://github.com/user-attachments/assets/ff3bb252-3cbc-4be9-86ed-4f1d6c3e6f48)
