### ISSUE TITLE
🚀 [ Feature ]: 大佬你好，希望能添加一个一键领取vip每日奖励的功能

### ISSUE THREAD

**Issue by FunnyMudChouPee** [LauZzL/leitingzhanji-ui#90]
#### 你希望增加的功能？
新增一个一键领取每日vip礼包

#### 为什么？
根据vip贵族等级，每日有不同数量的vip每日礼包，但是有时候要点很多次就比较烦，如果能加一个一键领取vip每日礼包就方便很多

**Comment by LauZzL** [comment]
没有VIP

**Comment by ASCIIX** [comment]
数据包已提交。
