### ISSUE TITLE
🐛 [ Bug ]: 获取封包数据失败

### ISSUE THREAD

**Issue by mortalref9527** [LauZzL/leitingzhanji-ui#91]
#### 您使用的版本？
3.1.2

#### 系统版本？
win10

#### 您遇到了什么问题？
获取封包数据失败，重启后又好了

#### 请提供错误截图？
![QQ20241005-072009](https://github.com/user-attachments/assets/51364655-4c55-4dd3-b8ab-ced55aaaf45a)
![QQ20241005-072026](https://github.com/user-attachments/assets/33c97a57-8bc8-45ff-ac2c-754ef90b2d4d)

**Comment by ASCIIX** [comment]
请求过快，IP被封，请更换IP或者重启。

**Comment by LauZzL** [comment]
不是BUG，可能请求量过大导致数据拥堵
