### ISSUE TITLE
🐛 [ Bug ]: js功能页，“运行”功能无效果

### ISSUE THREAD

**Issue by Mofan1379** [LauZzL/leitingzhanji-ui#94]
#### 您使用的版本？
网易云V3.1.3

#### 系统版本？
win1

#### 您遇到了什么问题？
js功能页，“运行”功能无效果，点击后会提示“运行完毕”，但实际没运行，且无日志

#### 请提供错误截图？
![Snipaste_2024-10-08_22-23-03](https://github.com/user-attachments/assets/d911f9cc-8ab8-4ee8-966f-cc936a9e49f1)

**Comment by LauZzL** [comment]
在下个版本修复
