### ISSUE TITLE
🤔 [ Question ]: 程序初始化还是无法捕获数据

### ISSUE THREAD

**Issue by Shikicn** [LauZzL/leitingzhanji-ui#96]
### 系统版本
Windows 10 专业版
22H2

### 程序版本
3.1.14

### 详细描述你的问题
网易云初始化后，打开游戏，并没有捕获到数据，重新载入游戏也试过了，也没有用，请问这是怎么回事呢？

### 截图 (如果可以)
![image](https://github.com/user-attachments/assets/3782ac58-fadd-461f-8fdd-b4d96335065d)

**Comment by LauZzL** [comment]
需要js-hook 目前还仍在编码中
