### ISSUE TITLE
🚀 [ Feature ]: 请问可以刷体力或者钻石吗

### ISSUE THREAD

**Issue by qqb-007** [LauZzL/leitingzhanji-ui#98]

**Comment by qqb-007** [comment]
请问可以刷体力或者钻石吗

**Comment by LauZzL** [comment]
永远不会。

[支持功能](https://lauzzl.github.io/leitingzhanji-docs/guide/basic-function.html)

**Comment by ASCIIX** [comment]
只要你能帮我刷99999999999体力，我就能给你刷999999999999999999钻石。
